language: python

install:
  - pip install codecov

script:
  - coverage run tests.py
  - curl -Os https://uploader.codecov.io/latest/linux/codecov 
  - chmod +x codecov 
  - ./codecov
  
after_success:
  - codecov

